active: "current"
configs:
  current: # All data loaded til 2026-01-15
    defaults:
      base: "~/Bucket/HELPOUT/"
      dataout: false
    scripts:
      helpy_html2csv:
        input: "data/20260202_IMS_Anfallstagebuch/"
        output: "output/helpy_html2csv/"
        dataout: true